
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package esercitazione5;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int CHAR_CONST = 60;
  public static final int POW = 45;
  public static final int CHAR = 15;
  public static final int GE = 52;
  public static final int UMINUS = 14;
  public static final int INTEGER_CONST = 58;
  public static final int INTEGER = 12;
  public static final int SEMI = 6;
  public static final int OUT = 18;
  public static final int INIT = 4;
  public static final int MINUS = 42;
  public static final int FOR = 19;
  public static final int WRITE = 30;
  public static final int NOT = 55;
  public static final int AND = 53;
  public static final int LT = 49;
  public static final int RPAR = 33;
  public static final int OR = 54;
  public static final int IN = 22;
  public static final int BOOL = 11;
  public static final int COMMA = 7;
  public static final int DIV = 44;
  public static final int PLUS = 41;
  public static final int LOOP = 28;
  public static final int ASSIGN = 37;
  public static final int MAIN = 2;
  public static final int IF = 20;
  public static final int WRITELN = 31;
  public static final int ID = 56;
  public static final int LE = 50;
  public static final int EOF = 0;
  public static final int RETURN = 38;
  public static final int TRUE = 39;
  public static final int error = 1;
  public static final int PIPE = 8;
  public static final int VOID = 16;
  public static final int EQ = 47;
  public static final int LBRACK = 34;
  public static final int REAL = 13;
  public static final int TIMES = 43;
  public static final int COLON = 36;
  public static final int ELSE = 25;
  public static final int RBRACK = 35;
  public static final int READ = 29;
  public static final int TO = 27;
  public static final int WHILE = 26;
  public static final int STR_CONCAT = 46;
  public static final int LET = 21;
  public static final int REAL_CONST = 59;
  public static final int THEN = 24;
  public static final int NE = 48;
  public static final int END = 23;
  public static final int LPAR = 32;
  public static final int STRING = 10;
  public static final int DEF = 17;
  public static final int FALSE = 40;
  public static final int STRING_CONST = 57;
  public static final int GT = 51;
  public static final int VAR = 9;
  public static final int DO = 3;
  public static final int STEP = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAIN",
  "DO",
  "INIT",
  "STEP",
  "SEMI",
  "COMMA",
  "PIPE",
  "VAR",
  "STRING",
  "BOOL",
  "INTEGER",
  "REAL",
  "UMINUS",
  "CHAR",
  "VOID",
  "DEF",
  "OUT",
  "FOR",
  "IF",
  "LET",
  "IN",
  "END",
  "THEN",
  "ELSE",
  "WHILE",
  "TO",
  "LOOP",
  "READ",
  "WRITE",
  "WRITELN",
  "LPAR",
  "RPAR",
  "LBRACK",
  "RBRACK",
  "COLON",
  "ASSIGN",
  "RETURN",
  "TRUE",
  "FALSE",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "POW",
  "STR_CONCAT",
  "EQ",
  "NE",
  "LT",
  "LE",
  "GT",
  "GE",
  "AND",
  "OR",
  "NOT",
  "ID",
  "STRING_CONST",
  "INTEGER_CONST",
  "REAL_CONST",
  "CHAR_CONST"
  };
}

